# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('province', models.CharField(blank=True, max_length=10)),
                ('record_time', models.DateTimeField()),
                ('alarm_type', models.CharField(blank=True, max_length=80)),
                ('filed', models.IntegerField()),
                ('filed2', models.IntegerField()),
            ],
        ),
    ]
